version: 2.1
executors:
  node:
    docker:
      - image: cypress/browsers:node16.14.0-chrome99-ff97
    working_directory: ~/repo
    resource_class: small
jobs:
  build:
    executor: node
    steps:
      - checkout

      # Install deps and run unit tests
      - run: npm ci
      # - run: npm test

      # Install the package as dependency and test that it works in a browser
      - run: npm run build
      - run:
          command: npm ci
          working_directory: e2e
      - run:
          command: npm run build
          working_directory: e2e
      - run:
          command: npx http-server www
          working_directory: e2e
          background: true
      - run:
          command: npm run cy:run
          working_directory: e2e

workflows:
  version: 2

  build-and-test:
    jobs:
      - build
